// Display-only translations. API values and state comparisons remain unchanged.
const labels: Readonly<Record<string, string>> = {
  Understanding: "目标理解",
  Planning: "调查规划",
  "Business Investigation": "业务调查",
  "Policy Retrieval": "政策检索",
  Synthesis: "结论生成",
  "Action Proposal": "行动提议",
  READY: "就绪",
  RUNNING: "调查中",
  UNAVAILABLE: "服务不可用",
  RECEIVED: "已接收问题",
  GOAL_UNDERSTOOD: "已理解目标",
  NEEDS_CLARIFICATION: "需要补充信息",
  PLANNED: "已完成规划",
  TOOL_SELECTED: "已选择 Tool",
  TOOL_EXECUTED: "Tool 已执行",
  INVESTIGATING: "调查中",
  INVESTIGATION_COMPLETE: "调查完成",
  DRAFT_READY: "分析草稿已生成",
  AWAITING_APPROVAL: "待人工审批",
  ACTION_APPROVED: "行动已批准",
  ACTION_REJECTED: "行动已拒绝",
  ACTION_EXECUTED: "行动已执行",
  ACTION_FAILED: "行动执行失败",
  RUNTIME_STOPPED: "运行已停止",
  ERROR: "运行出错",
  UNSUPPORTED: "暂不支持该请求",
  COMPLETED: "已完成",
  MODEL_ERROR: "模型调用错误",
  TOOL_ERROR: "Tool 执行错误",
  MODEL_RETRY_EXHAUSTED: "模型重试次数已耗尽",
  MAX_AGENT_STEPS_EXCEEDED: "已达到调查步骤上限",
  MAX_LLM_CALLS_EXCEEDED: "已达到 LLM 调用上限",
  MAX_TOOL_CALLS_EXCEEDED: "已达到 Tool 调用上限",
  MAX_RETRIES_EXCEEDED: "已达到总重试上限",
  REPEATED_ACTION_LOOP: "检测到重复动作循环",
  STAGNANT_LOOP: "调查未取得新进展",
  TOOL_TIMEOUT: "Tool 执行超时",
  TOKEN_BUDGET_EXCEEDED: "已达到 Token 预算上限",
  RUN_UNAVAILABLE: "调查服务暂不可用",
  PROVIDER_TIMEOUT: "模型服务响应超时",
  LOW: "低",
  MEDIUM: "中",
  EAST_CHINA: "华东",
  NORTH_CHINA: "华北",
  SOUTH_CHINA: "华南",
  WEST_CHINA: "西部",
  understand_goal: "目标理解",
  plan: "调查规划",
  select_tool: "Tool 选择",
  execute_tool: "Tool 执行",
  review_progress: "进度审阅",
  synthesize: "结论生成",
  propose_action: "行动提议",
};

export function displayLabel(value: string): string {
  return labels[value] ?? value;
}
